# Generated by Django 5.2.4 on 2025-07-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_mentor_alter_botuser_options_alter_botuser_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermentor',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bot.botuser'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
