# Generated by Django 5.2.4 on 2025-07-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_usermentor_mentor_alter_botuser_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermentor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usermentor',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='usermentor',
            name='user',
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='achievement-files/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='UserMentor',
        ),
    ]
