# Generated by Django 5.2.4 on 2025-07-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
