# Generated by Django 5.2.4 on 2025-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitation_photo',
            field=models.ImageField(default='', upload_to='invitation-photos/'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('event', 'user')},
        ),
    ]
