# Generated by Django 5.2.4 on 2025-07-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_event_invitation_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
    ]
