# Generated by Django 5.2.4 on 2025-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_event_end_date_remove_event_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='invitation-photos/'),
        ),
    ]
