# Generated by Django 5.2.4 on 2025-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
